header:
  license:
    spdx-id: LicenseRef-Proprietary
    copyright-owner: adcl.io
    content: |
      Copyright (c) 2025 adcl.io
      All Rights Reserved.

      This software is proprietary and confidential. Unauthorized copying,
      distribution, or use of this software is strictly prohibited.

  language:
    JavaScript:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
      comment_style_id: SlashAsterisk

  paths-ignore:
    # Dependencies
    - '**/node_modules/**'
    - '**/venv/**'
    - '**/__pycache__/**'
    - '**/dist/**'
    - '**/build/**'
    - '**/.venv/**'

    # Generated files
    - '**/package-lock.json'
    - '**/yarn.lock'
    - '**/pnpm-lock.yaml'

    # Documentation
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'README'
    - 'docs/**/*.txt'

    # Configuration files
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.toml'
    - '**/*.ini'
    - '**/*.conf'
    - '.gitignore'
    - '.dockerignore'
    - '.env*'

    # Docker
    - '**/Dockerfile*'
    - 'docker-compose*.yml'

    # Test fixtures and data
    - '**/fixtures/**'
    - '**/test-data/**'
    - '**/snapshots/**'

    # Logs and temporary files
    - 'logs/**'
    - '**/*.log'
    - '**/tmp/**'
    - '**/temp/**'

    # IDE and system files
    - '**/.vscode/**'
    - '**/.idea/**'
    - '**/*.swp'
    - '**/*.swo'
    - '**/.DS_Store'

    # Registry and package files
    - 'registry/**'
    - '**/metadata.json'

    # Workflows (JSON files)
    - 'workflows/**'
    - 'agent-teams/**'
    - 'agent-definitions/**'

    # Scripts
    - '**/*.sh'

    # Git
    - '.git/**'

  paths:
    - '**/*.py'
    - '**/*.js'
    - '**/*.jsx'
    - '**/*.ts'
    - '**/*.tsx'

  comment: on-failure
