#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
WIKI_REPO_URL="https://github.com/adcl-io/adcl-community.wiki.git"
WIKI_DIR="adcl-community.wiki"
DOCS_SOURCE="docs/wiki"

echo -e "${GREEN}=== ADCL Community Wiki Publisher ===${NC}\n"

# Check if docs/wiki exists
if [ ! -d "$DOCS_SOURCE" ]; then
    echo -e "${RED}Error: $DOCS_SOURCE directory not found${NC}"
    exit 1
fi

# Count documentation files
DOC_COUNT=$(find "$DOCS_SOURCE" -name "*.md" | wc -l)
echo -e "Found ${GREEN}$DOC_COUNT${NC} documentation files to publish\n"

# Clone or update wiki repository
if [ -d "$WIKI_DIR" ]; then
    echo -e "${YELLOW}Wiki repository already exists, updating...${NC}"
    cd "$WIKI_DIR"
    git pull origin master
    cd ..
else
    echo -e "${YELLOW}Cloning wiki repository...${NC}"
    git clone "$WIKI_REPO_URL" "$WIKI_DIR"
fi

# Check if clone was successful
if [ ! -d "$WIKI_DIR" ]; then
    echo -e "${RED}Error: Failed to clone wiki repository${NC}"
    echo -e "${YELLOW}Make sure you have access to: $WIKI_REPO_URL${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Wiki repository ready${NC}\n"

# Copy documentation files
echo -e "${YELLOW}Copying documentation files...${NC}"
cp -v "$DOCS_SOURCE"/*.md "$WIKI_DIR/"

echo -e "${GREEN}✓ Files copied${NC}\n"

# Commit and push
cd "$WIKI_DIR"

# Check if there are changes
if git diff --quiet && git diff --cached --quiet; then
    echo -e "${YELLOW}No changes to commit${NC}"
    cd ..
    exit 0
fi

echo -e "${YELLOW}Committing changes...${NC}"

# Add all markdown files
git add *.md

# Create commit message
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
COMMIT_MSG="Update documentation - $TIMESTAMP

- Updated $DOC_COUNT documentation files
- Source: demo-sandbox/docs/wiki/
- Auto-generated by post-community-wiki.sh"

git commit -m "$COMMIT_MSG"

echo -e "${GREEN}✓ Changes committed${NC}\n"

# Push to GitHub
echo -e "${YELLOW}Pushing to GitHub wiki...${NC}"
git push origin master

echo -e "${GREEN}✓ Successfully pushed to wiki${NC}\n"

cd ..

# Print wiki URL
echo -e "${GREEN}=== Documentation Published ===${NC}"
echo -e "Wiki URL: ${GREEN}https://github.com/adcl-io/adcl-community/wiki${NC}"
echo -e "\nPublished pages:"
ls -1 "$WIKI_DIR"/*.md | xargs -n 1 basename | sed 's/.md$//' | sed 's/^/  - /'

echo -e "\n${GREEN}Done!${NC}"
